services:
  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    buildCommand: docker build -t frontend ./frontend
    startCommand: docker run -p 5173:5173 frontend
    envVars:
      - key: REACT_BACKEND_URL
        value: http://backend:5000

  - type: web
    name: backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    buildCommand: docker build -t backend ./backend
    startCommand: docker run -p 5000:5000 backend
    envVars:
      - key: DATABASE_URL
        value: postgres://postgres:mysecretpassword@postgres:5432/postgres

databases:
  - name: postgres
    plan: free
    region: oregon
    diskSizeGB: 10
    user: postgres
    databaseName: postgres
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all IPs
