services:
  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    buildCommand: docker build -t frontend ./frontend
    envVars:
      - key: REACT_BACKEND_URL
        value: http://backend:5000

  - type: web
    name: backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    buildCommand: docker build -t backend ./backend
    envVars:
      - key: DATABASE_URL
        value: postgres://intouchuser:mysecretpassword@postgres:5432/intouch

databases:
  - name: postgres
    plan: free
    region: oregon
    diskSizeGB: 10
    user: intouchuser
    databaseName: intouch
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all IPs
